### ISSUE TITLE
Template minimamente funcional

### ISSUE THREAD

**Issue by pedrotst** [gessikete/sistemas_operacionais#1]
Preferencialmente lendo o arquivo. Só pra começar de algum lugar mesmo.

**Comment by pedrotst** [comment]
@gessikete, pode testar pra gente? Daí se tiver tudo ok dá close na issue e anda com o ticket no kanban.
Senão tiver algum comentário tu volta o ticket e avisa aqui :)

**Comment by gessikete** [comment]
os recursos estão mostrando true e false, tem q mostrar o número.

**Comment by gessikete** [comment]
Uma vez q todos os processos são lidos e o output exibido, o programa não finaliza.

**Comment by pedrotst** [comment]
no meu entendimento não tem que terminar mesmo não, pq é como se a cpu estivesse checando se tem algo em alguma fila pra ser executado saca?
Que é exatamente como foi implementado na verdade

**Comment by gessikete** [comment]
então beleza.
