### ISSUE TITLE
Implementar modelo de memória

### ISSUE THREAD

**Issue by pedrotst** [gessikete/sistemas_operacionais#2]

**Comment by pedrotst** [comment]
@gessikete, @ytalocarvalho commitei isto, se importam de rodar teste pra ver se tá funcionando mesmo?

**Comment by gessikete** [comment]
caso a quantidade a alocar seja maior que a quantidade  de espaços disponíveis, nenhuma mensagem é mostrada e nenhuma alocação é feita

**Comment by pedrotst** [comment]
Adcionado mensagem Resource Unnavailable Memory to PID 1

**Comment by gessikete** [comment]
lindo
